name: Build MegaDumper

on:
  push: # Trigger on pushes to any branch

jobs:
  build:
    runs-on: windows-latest  # Run on Windows virtual machines

    steps:
      - uses: actions/checkout@v3 # Checkout code from repository

      - name: Use .NET Core tools
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '2.0.x' # Update as needed for your project

      - name: Restore dependencies
        run: dotnet restore MegaDumper.sln

      - name: Build (x64)
        run: dotnet build MegaDumper.sln /configuration:Release /platform:x64

      - name: Publish (Optional)
        # You can add a step to publish the build artifacts here
        # Only uncomment if you need to publish the built application
        # run: ...
